<a href="https://colab.research.google.com/github/DanawiraPrama/sg-prop-dashboard/blob/main/DataGovSG.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Overview

This Jupyter notebook makes it easy to :

1. Get the dataset and column metadata programmatically
2. Load CSV files automatically into a pandas dataframe so you can do the fun explorations

# Setup
1. Paste the dataset ID you copied into the cell below
2. Run All Cells (click `Runtime` -> `Run All`)

In [ ]:
DATASET_ID = "PASTE_DATASET_ID_HERE" # e.g. "d_69b3380ad7e51aff3a7dcc84eba52b8a"
API_KEY = "PASTE_API_KEY_HERE" #e.g. "v2:a7ae10..."

## Dataset and Column Metadata

In [ ]:
import json
import requests

s = requests.Session()
s.headers.update({'referer': 'https://colab.research.google.com'})
if API_KEY and API_KEY != "PASTE_API_KEY_HERE":
    s.headers['x-api-key'] = API_KEY
s.headers.update(s.headers)
base_url = "https://api-production.data.gov.sg"
url = base_url + f"/v2/public/api/datasets/{DATASET_ID}/metadata"
print(url)
response = s.get(url)
data = response.json()['data']
columnMetadata = data.pop('columnMetadata', None)

print("Dataset Metadata:")
print(json.dumps(data, indent=2))

print("\nColumns:\n", list(columnMetadata['map'].values()))

https://api-production.data.gov.sg/v2/public/api/datasets/d_69b3380ad7e51aff3a7dcc84eba52b8a/metadata
Dataset Metadata:
{
  "datasetId": "d_69b3380ad7e51aff3a7dcc84eba52b8a",
  "createdAt": "2024-07-24T16:58:00+08:00",
  "name": "COE Bidding Results / Prices",
  "collectionIds": [],
  "description": "COE bidding and prices results for each bidding exercise.\nCategory A\n- For COEs obtained before the May 2022 1st COE bidding exercise: Car with engine capacity up to 1,600cc and Maximum Power Output up to 97kW (130bhp)\n- For COEs obtained from the May 2022 1st COE bidding exercise onwards:\n- Non-fully electric cars with engines up to 1,600cc and Maximum Power Output up to 97kW (130bhp); and fully electric cars with Maximum Power Output up to 110kW (147bhp)\nCategory B\n- For COEs obtained before the May 2022 1st COE bidding exercise:\n- Car with engine capacity above 1,600cc or Maximum Power Output above 97kW (130bhp)\n- For COEs obtained from the May 2022 1st COE bidding exercise onwards:\n- Non-fully electric cars with engines above 1,600cc or Maximum Power Output above 97kW (130bhp); and fully electric cars with Maximum Power Output above 110kW (147bhp)\n\nCategory C*\n- Goods vehicle and bus\n\\n\n\nCategory D\n- Motorcycle\n\n\nCategory E*\n- Open \u2013 all except motorcycle\n\n\n*You can only transfer COEs in Categories C and E once if you bid for them as an individual. If your bid is under a company, business or organisation, the COEs cannot be transferred. COEs in Categories A, B and D cannot be transferred.\n\n\nFor more information: https://onemotoring.lta.gov.sg/content/onemotoring/home/buying/upfront-vehicle-costs/certificate-of-entitlement--coe-.html#:~:text=All%20vehicles%20in%20Singapore%20require,the%20road%20for%2010%20years.",
  "format": "CSV",
  "lastUpdatedAt": "2025-07-10T09:46:34+08:00",
  "managedBy": "Land Transport Authority",
  "coverageStart": "2010-01-01T08:00:00+08:00",
  "coverageEnd": "2025-07-01T08:00:00+08:00",
  "contactEmails": [
    "feedback@data.gov.sg"
  ],
  "datasetSize": 74489
}

Columns:
 ['month', 'bidding_no', 'vehicle_class', 'quota', 'bids_success', 'bids_received', 'premium']

## Download File

In [ ]:
import time
import pandas as pd

def download_file(DATASET_ID, API_KEY=None):

  headers = {"Content-Type": "application/json"}
  if API_KEY:
      headers["x-api-key"] = API_KEY
  # initiate download
  initiate_download_response = s.get(
      f"https://api-open.data.gov.sg/v1/public/api/datasets/{DATASET_ID}/initiate-download",
      headers=headers,
      json={}
  )
  print(initiate_download_response.json()['data']['message'])

  # poll download
  MAX_POLLS = 5
  for i in range(MAX_POLLS):
    poll_download_response = s.get(
        f"https://api-open.data.gov.sg/v1/public/api/datasets/{DATASET_ID}/poll-download",
        headers=headers,
        json={}
    )
    print("Poll download response:", poll_download_response.json())
    if "url" in poll_download_response.json()['data']:
      print(poll_download_response.json()['data']['url'])
      DOWNLOAD_URL = poll_download_response.json()['data']['url']
      df = pd.read_csv(DOWNLOAD_URL)

      display(df.head())
      print("\nDataframe loaded!")
      return df
    if i == MAX_POLLS - 1:
      print(f"{i+1}/{MAX_POLLS}: No result found, possible error with dataset, please try again or let us know at https://go.gov.sg/datagov-supportform\n")
    else:
      print(f"{i+1}/{MAX_POLLS}: No result yet, continuing to poll\n")
    time.sleep(3)

df = download_file(DATASET_ID)

Download successfully initiated. Proceed to poll download
Poll download response: {'code': 0, 'data': {'status': 'DOWNLOAD_SUCCESS', 'url': 'https://s3.ap-southeast-1.amazonaws.com/table-downloads-ingest.data.gov.sg/d_69b3380ad7e51aff3a7dcc84eba52b8a/bc089cff69444272a8741daec72d4a267ad4d483b2c554fd0e17c39f5c52a762.csv?AWSAccessKeyId=ASIAU7LWPY2WDFGT5KPD&Expires=1753248829&Signature=7BpnFoFcjB6ZQ6Zjepo95YOxMas%3D&X-Amzn-Trace-Id=Root%3D1-6880662d-716df5e1322214ae6d4f15a5%3BParent%3D49239bdf0f706aaa%3BSampled%3D0%3BLineage%3D1%3Affb76583%3A0&response-content-disposition=attachment%3B%20filename%3D%22COEBiddingResultsPrices.csv%22&x-amz-security-token=IQoJb3JpZ2luX2VjEOT%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDmFwLXNvdXRoZWFzdC0xIkYwRAIgN4ZVn1P%2FIZuChloS9vJt1VhQ4Z5bNItYe23UQB1pBOcCIHrQh5%2B0tSVg3H6Ur84kqJLTuKJ6ivl5GrgQM7CKfiwzKrMDCP3%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQBBoMMzQyMjM1MjY4NzgwIgz9ETKYCInG97z62sQqhwNnC7z7hSWjZ9tVpdlPFJYsZjwH5SqLYadb618ZMC%2BdsmbqPiLrMHd5%2FVUt77P3FPve48UT7kySCNDdT6sqeG01TBo1NiPcIXOiHSFq7k5Hq88epik8CjBWqM5EKz77H4gub%2FXVDa2eDg4AATVOlaeTb8eBBo4SxyTKtjiN5asv2wIVIugNKxGsQ2Sy7g6o9iaHoKBzVoeh3r%2FBJIS8JFGjVE004T3SNw2o49F3Zy%2BttUGLhvla%2FuXfFUQx1724Tie5kERXGADSD%2BgyQ6rCyjAeueCCh3GwE%2FatxSchSK%2FCMC5K%2BrQEGvvXPZf4eff6dwMsywykx8CH4p9hHavwRVmnaFoFXMYvnFkHL%2FqU3kF%2BQ9xSjJcoRY3xsKq3UWcmwf2TYURUKmlLKRo3liN609SPXnN%2BNsbNOt5%2BH20mYwkrZ%2FbL6gyOL6SV4FTGv3l4p4IlDfSZu16t4GUEhDazxOxeqZEhuiF7D3HEpgs87fqg2TBcOugmu95CEh7fWGhllUb5UVOjZn3TMMDDgcQGOp4B7GSYs303GlZHc2hxpKeZ2as6%2BLJYLECAmCOHeQ7SqsvE%2FGUm0%2Fj1nmGL4%2FiO3hNcGQe3gbNXNGdBDRWI%2F2ijybwRRmPZhzOp%2FAN9xVzhMyuIBTPH8YBheCE2eq%2Fp7Nbz8QlNwdVbFKmlnR5c3ksVUQfW0B5UMY2BsXWCIyUEzSWSwCNKJ7fhp4PZJYTcrlsJ0tjNksNcWcZKbUBXknI%3D'}, 'errorMsg': ''}
https://s3.ap-southeast-1.amazonaws.com/table-downloads-ingest.data.gov.sg/d_69b3380ad7e51aff3a7dcc84eba52b8a/bc089cff69444272a8741daec72d4a267ad4d483b2c554fd0e17c39f5c52a762.csv?AWSAccessKeyId=ASIAU7LWPY2WDFGT5KPD&Expires=1753248829&Signature=7BpnFoFcjB6ZQ6Zjepo95YOxMas%3D&X-Amzn-Trace-Id=Root%3D1-6880662d-716df5e1322214ae6d4f15a5%3BParent%3D49239bdf0f706aaa%3BSampled%3D0%3BLineage%3D1%3Affb76583%3A0&response-content-disposition=attachment%3B%20filename%3D%22COEBiddingResultsPrices.csv%22&x-amz-security-token=IQoJb3JpZ2luX2VjEOT%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDmFwLXNvdXRoZWFzdC0xIkYwRAIgN4ZVn1P%2FIZuChloS9vJt1VhQ4Z5bNItYe23UQB1pBOcCIHrQh5%2B0tSVg3H6Ur84kqJLTuKJ6ivl5GrgQM7CKfiwzKrMDCP3%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQBBoMMzQyMjM1MjY4NzgwIgz9ETKYCInG97z62sQqhwNnC7z7hSWjZ9tVpdlPFJYsZjwH5SqLYadb618ZMC%2BdsmbqPiLrMHd5%2FVUt77P3FPve48UT7kySCNDdT6sqeG01TBo1NiPcIXOiHSFq7k5Hq88epik8CjBWqM5EKz77H4gub%2FXVDa2eDg4AATVOlaeTb8eBBo4SxyTKtjiN5asv2wIVIugNKxGsQ2Sy7g6o9iaHoKBzVoeh3r%2FBJIS8JFGjVE004T3SNw2o49F3Zy%2BttUGLhvla%2FuXfFUQx1724Tie5kERXGADSD%2BgyQ6rCyjAeueCCh3GwE%2FatxSchSK%2FCMC5K%2BrQEGvvXPZf4eff6dwMsywykx8CH4p9hHavwRVmnaFoFXMYvnFkHL%2FqU3kF%2BQ9xSjJcoRY3xsKq3UWcmwf2TYURUKmlLKRo3liN609SPXnN%2BNsbNOt5%2BH20mYwkrZ%2FbL6gyOL6SV4FTGv3l4p4IlDfSZu16t4GUEhDazxOxeqZEhuiF7D3HEpgs87fqg2TBcOugmu95CEh7fWGhllUb5UVOjZn3TMMDDgcQGOp4B7GSYs303GlZHc2hxpKeZ2as6%2BLJYLECAmCOHeQ7SqsvE%2FGUm0%2Fj1nmGL4%2FiO3hNcGQe3gbNXNGdBDRWI%2F2ijybwRRmPZhzOp%2FAN9xVzhMyuIBTPH8YBheCE2eq%2Fp7Nbz8QlNwdVbFKmlnR5c3ksVUQfW0B5UMY2BsXWCIyUEzSWSwCNKJ7fhp4PZJYTcrlsJ0tjNksNcWcZKbUBXknI%3D

,month,bidding_no,vehicle_class,quota,bids_success,bids_received,premium
0,2010-01,1,Category A,1152,1145,1342,18502
1,2010-01,1,Category B,687,679,883,19190
2,2010-01,1,Category C,173,173,265,19001
3,2010-01,1,Category D,373,365,509,889
4,2010-01,1,Category E,586,567,1011,19889

Dataframe loaded!

In [ ]:
df.describe()

        bidding_no        quota        premium
count  1835.000000  1835.000000    1835.000000
mean      1.498638   565.764578   50516.278474
std       0.500134   420.596173   32259.684933
min       1.000000    43.000000     852.000000
25%       1.000000   292.000000   29085.000000
50%       1.000000   434.000000   49012.000000
75%       2.000000   659.500000   72051.500000
max       2.000000  2272.000000  158004.000000

In [5]:
import pandas as pd
import requests
import time

# Re-establishing session and variables if lost
s = requests.Session()
s.headers.update({'referer': 'https://colab.research.google.com'})
if 'API_KEY' not in globals():
    API_KEY = "PASTE_API_KEY_HERE"
if 'DATASET_ID' not in globals():
    DATASET_ID = "d_69b3380ad7e51aff3a7dcc84eba52b8a"

def get_df(dataset_id):
    headers = {"Content-Type": "application/json"}
    init = s.get(f"https://api-open.data.gov.sg/v1/public/api/datasets/{dataset_id}/initiate-download", headers=headers)
    for i in range(5):
        poll = s.get(f"https://api-open.data.gov.sg/v1/public/api/datasets/{dataset_id}/poll-download", headers=headers)
        res = poll.json()
        if "url" in res.get('data', {}):
            return pd.read_csv(res['data']['url'])
        time.sleep(2)
    return None

# Load and filter
try:
    df = get_df(DATASET_ID)
    if df is not None:
        df['month_dt'] = pd.to_datetime(df['month'])
        df_2026 = df[df['month_dt'].dt.year == 2026]
        print(f"Total records in 2026: {len(df_2026)}")
        display(df_2026.head())
    else:
        print("Failed to load data.")
except Exception as e:
    print(f"An error occurred: {e}")

Total records in 2026: 50

,month,bidding_no,vehicle_class,quota,bids_success,bids_received,premium,month_dt
1890,2026-01,1,Category A,1285,"1,284","1,658",102009,2026-01-01
1891,2026-01,1,Category B,824,821,"1,128",119100,2026-01-01
1892,2026-01,1,Category C,287,286,394,75503,2026-01-01
1893,2026-01,1,Category D,544,527,639,8689,2026-01-01
1894,2026-01,1,Category E,278,247,528,122000,2026-01-01

# HDB Resale Prices Exploration
Fetching data for dataset ID: `d_8b84c4ee58e3cfc0ece0d773c8ca6abc`

In [11]:
import requests
import pandas as pd

dataset_id = "d_8b84c4ee58e3cfc0ece0d773c8ca6abc"
# Increasing limit to 1000 records
url = f"https://data.gov.sg/api/action/datastore_search?resource_id={dataset_id}&sort=_id%20desc&limit=1000"

response = requests.get(url)
if response.status_code == 200:
    data = response.json()
    records = data['result']['records']
    df_hdb = pd.DataFrame(records)

    if not df_hdb.empty:
        print(f"Successfully fetched {len(df_hdb)} records.")
        # Save to CSV
        file_name = "hdb_resale_2026_data.csv"
        df_hdb.to_csv(file_name, index=False)
        print(f"Data saved to {file_name}")
        display(df_hdb.head())
    else:
        print("No records found in the HDB dataset.")
else:
    print(f"Failed to fetch data. Status code: {response.status_code}")

Successfully fetched 1000 records.
Data saved to hdb_resale_2026_data.csv

,_id,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price
0,232406,2026-05,YISHUN,MULTI-GENERATION,666,YISHUN AVE 4,04 TO 06,164.00,Multi Generation,1987,60 years 08 months,1120000
1,232405,2026-05,YISHUN,EXECUTIVE,828,YISHUN ST 81,07 TO 09,145.00,Apartment,1988,60 years 09 months,1068888
2,232404,2026-04,YISHUN,EXECUTIVE,827,YISHUN ST 81,01 TO 03,145.00,Maisonette,1987,60 years 06 months,960000
3,232403,2026-03,YISHUN,EXECUTIVE,877,YISHUN ST 81,07 TO 09,142.00,Apartment,1987,60 years 10 months,980000
4,232402,2026-03,YISHUN,EXECUTIVE,836,YISHUN ST 81,10 TO 12,146.00,Maisonette,1988,61 years,995000

In [10]:
import pandas as pd

# The df_hdb variable now contains the 2026 records seen in the previous cell
# We ensure 'month' is treated as a string for filtering or converted to datetime
df_hdb_2026 = df_hdb[df_hdb['month'].str.contains('2026')]

print(f"Total HDB resale records for 2026 found in the current batch: {len(df_hdb_2026)}")
if not df_hdb_2026.empty:
    display(df_hdb_2026.sort_values('month'))
else:
    print("No records found for the year 2026 in the current dataframe.")

Total HDB resale records for 2026 found in the current batch: 100

,_id,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price
33,232373,2026-01,YISHUN,5 ROOM,851,YISHUN ST 81,04 TO 06,127.00,Improved,1988,61 years 02 months,768000
26,232380,2026-01,YISHUN,EXECUTIVE,325,YISHUN CTRL,10 TO 12,146.00,Maisonette,1988,61 years 11 months,888000
27,232379,2026-01,YISHUN,EXECUTIVE,405,YISHUN AVE 6,04 TO 06,142.00,Apartment,1988,61 years 08 months,880000
65,232341,2026-01,YISHUN,5 ROOM,209,YISHUN ST 21,07 TO 09,121.00,Improved,1985,58 years 05 months,600000
13,232393,2026-01,YISHUN,EXECUTIVE,643,YISHUN ST 61,10 TO 12,142.00,Apartment,1987,60 years 09 months,825000
...,...,...,...,...,...,...,...,...,...,...,...,...
14,232392,2026-05,YISHUN,EXECUTIVE,277,YISHUN ST 22,07 TO 09,146.00,Maisonette,1985,58 years 04 months,868000
1,232405,2026-05,YISHUN,EXECUTIVE,828,YISHUN ST 81,07 TO 09,145.00,Apartment,1988,60 years 09 months,1068888
75,232331,2026-05,YISHUN,5 ROOM,798,YISHUN RING RD,01 TO 03,122.00,Improved,1986,59 years 06 months,660000
99,232307,2026-05,YISHUN,5 ROOM,289,YISHUN AVE 6,10 TO 12,122.00,Improved,1987,60 years 03 months,658000
71,232335,2026-06,YISHUN,5 ROOM,166,YISHUN RING RD,10 TO 12,121.00,Improved,1987,60 years 07 months,612000

In [12]:
# Calculate the count of records for the year 2026
count_2026 = df_hdb[df_hdb['month'].str.contains('2026', na=False)].shape[0]
print(f"There are exactly {count_2026} records for the year 2026 in the dataset we just downloaded.")

There are exactly 1000 records for the year 2026 in the dataset we just downloaded.

In [18]:
import requests
import pandas as pd
import time

dataset_id = "d_8b84c4ee58e3cfc0ece0d773c8ca6abc"
all_2026_records = []
limit = 1000
offset = 0

print("Manually scanning dataset for all 2026 records...")

while True:
    # We sort by ID descending to get the most recent data (including 2026) first
    url = f"https://data.gov.sg/api/action/datastore_search?resource_id={dataset_id}&sort=_id desc&limit={limit}&offset={offset}"

    response = requests.get(url)
    if response.status_code != 200:
        print(f"Error at offset {offset}: {response.status_code}")
        break

    data = response.json()
    records = data['result']['records']

    if not records:
        break

    # Filter records for 2026 in this batch
    batch_2026 = [r for r in records if '2026' in str(r.get('month', ''))]
    all_2026_records.extend(batch_2026)

    # If we find a record older than 2026, and we're sorting desc, we can potentially stop
    # but to be safe, we check if the entire batch is older than 2026
    oldest_in_batch = records[-1].get('month', '')
    if oldest_in_batch < '2026-01' and len(batch_2026) == 0:
        print("Reached records older than 2026. Stopping scan.")
        break

    offset += limit
    print(f"Processed {offset} records... Found {len(all_2026_records)} matches so far.")
    time.sleep(0.5)

df_final_2026 = pd.DataFrame(all_2026_records)
print(f"\nFinal Count of 2026 Records: {len(df_final_2026)}")
if not df_final_2026.empty:
    df_final_2026.to_csv('hdb_resale_full_2026.csv', index=False)
    display(df_final_2026.head())

Manually scanning dataset for all 2026 records...
Processed 1000 records... Found 1000 matches so far.
Processed 2000 records... Found 2000 matches so far.
Processed 3000 records... Found 3000 matches so far.
Processed 4000 records... Found 4000 matches so far.
Processed 5000 records... Found 5000 matches so far.
Processed 6000 records... Found 6000 matches so far.
Processed 7000 records... Found 7000 matches so far.
Processed 8000 records... Found 8000 matches so far.
Processed 9000 records... Found 9000 matches so far.
Processed 10000 records... Found 10000 matches so far.
Processed 11000 records... Found 10338 matches so far.
Reached records older than 2026. Stopping scan.

Final Count of 2026 Records: 10338

,_id,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price
0,232406,2026-05,YISHUN,MULTI-GENERATION,666,YISHUN AVE 4,04 TO 06,164.00,Multi Generation,1987,60 years 08 months,1120000
1,232405,2026-05,YISHUN,EXECUTIVE,828,YISHUN ST 81,07 TO 09,145.00,Apartment,1988,60 years 09 months,1068888
2,232404,2026-04,YISHUN,EXECUTIVE,827,YISHUN ST 81,01 TO 03,145.00,Maisonette,1987,60 years 06 months,960000
3,232403,2026-03,YISHUN,EXECUTIVE,877,YISHUN ST 81,07 TO 09,142.00,Apartment,1987,60 years 10 months,980000
4,232402,2026-03,YISHUN,EXECUTIVE,836,YISHUN ST 81,10 TO 12,146.00,Maisonette,1988,61 years,995000

In [19]:
import pandas as pd

# Split the dataframe into parts
df_part1 = df_final_2026.iloc[0:5000]
df_part2 = df_final_2026.iloc[5000:10000]
df_part3 = df_final_2026.iloc[10000:]

# Save to separate CSV files
df_part1.to_csv('hdb_resale_2026_part1.csv', index=False)
df_part2.to_csv('hdb_resale_2026_part2.csv', index=False)
df_part3.to_csv('hdb_resale_2026_part3.csv', index=False)

print(f"Part 1 saved: {len(df_part1)} records")
print(f"Part 2 saved: {len(df_part2)} records")
print(f"Part 3 saved: {len(df_part3)} records")

Part 1 saved: 5000 records
Part 2 saved: 5000 records
Part 3 saved: 338 records

In [20]:
import requests
import pandas as pd
import time

dataset_id = "d_8b84c4ee58e3cfc0ece0d773c8ca6abc"
all_2025_records = []
limit = 1000
offset = 0

print("Manually scanning dataset for all 2025 records...")

while True:
    # Sorting by ID descending to start from the most recent data
    url = f"https://data.gov.sg/api/action/datastore_search?resource_id={dataset_id}&sort=_id desc&limit={limit}&offset={offset}"

    response = requests.get(url)
    if response.status_code != 200:
        if response.status_code == 429:
            time.sleep(2)
            continue
        print(f"Error at offset {offset}: {response.status_code}")
        break

    data = response.json()
    records = data['result']['records']

    if not records:
        break

    # Filter records for 2025 in this batch
    batch_2025 = [r for r in records if '2025' in str(r.get('month', ''))]
    all_2025_records.extend(batch_2025)

    # Since we are sorting DESC, if we find a record older than 2025-01,
    # and the current batch has no 2025 records, we have passed the range.
    oldest_in_batch = records[-1].get('month', '')
    if oldest_in_batch < '2025-01' and len(batch_2025) == 0:
        # Small safety check: only stop if we are well past the 2025-2026 transition
        print(f"Reached records from {oldest_in_batch}. Stopping scan.")
        break

    offset += limit
    if offset % 5000 == 0:
        print(f"Processed {offset} records... Found {len(all_2025_records)} matches for 2025 so far.")
    time.sleep(0.3)

df_final_2025 = pd.DataFrame(all_2025_records)
print(f"\nFinal Count of 2025 Records: {len(df_final_2025)}")
if not df_final_2025.empty:
    df_final_2025.to_csv('hdb_resale_full_2025.csv', index=False)
    display(df_final_2025.head())
else:
    print("No records found for the year 2025.")

Manually scanning dataset for all 2025 records...
Processed 5000 records... Found 0 matches for 2025 so far.
Processed 10000 records... Found 0 matches for 2025 so far.
Processed 15000 records... Found 4662 matches for 2025 so far.
Processed 20000 records... Found 9662 matches for 2025 so far.
Processed 25000 records... Found 14662 matches for 2025 so far.
Processed 30000 records... Found 19662 matches for 2025 so far.
Processed 35000 records... Found 24662 matches for 2025 so far.
Reached records from 2024-02. Stopping scan.

Final Count of 2025 Records: 25086

,_id,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price
0,222068,2025-07,YISHUN,MULTI-GENERATION,633,YISHUN ST 61,01 TO 03,171.00,Multi Generation,1987,61 years 06 months,1095000
1,222067,2025-05,YISHUN,MULTI-GENERATION,632,YISHUN ST 61,04 TO 06,147.00,Multi Generation,1987,61 years 06 months,945000
2,222066,2025-10,YISHUN,EXECUTIVE,834,YISHUN ST 81,07 TO 09,142.00,Apartment,1988,61 years 04 months,990000
3,222065,2025-09,YISHUN,EXECUTIVE,834,YISHUN ST 81,04 TO 06,146.00,Maisonette,1988,61 years 04 months,990000
4,222064,2025-09,YISHUN,EXECUTIVE,877,YISHUN ST 81,10 TO 12,145.00,Maisonette,1987,61 years 03 months,980000

In [ ]:
import pandas as pd
import numpy as np

# Split the 2025 data into chunks of 5000
chunk_size = 5000
num_chunks = int(np.ceil(len(df_final_2025) / chunk_size))

print(f"Splitting {len(df_final_2025)} records into {num_chunks} files...")

for i in range(num_chunks):
    start = i * chunk_size
    end = start + chunk_size
    df_chunk = df_final_2025.iloc[start:end]
    file_name = f'hdb_resale_2025_part{i+1}.csv'
    df_chunk.to_csv(file_name, index=False)
    print(f"Saved {file_name} ({len(df_chunk)} records)")